---
title: "Trabalho aula 5 - MLP em séries continuas (Caso Ibovespa)"
author: "AfonsoBrandao"
date: "2023-03-29"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Setup dos Dados

```{r ibovespa}
#install.packages("RSNNS")
library("RSNNS")

bd <- read.table("ibovespa_3.csv", header = TRUE, sep = ";")
x <- bd[, 1]

x <- normalizeData(x, type = "0_1")
plot(x)

epoch <- 20000
```
```{r funções de cálculo}
previsao_demanda <-function(janela) {
  tam_janela = strtoi(janela)
  nro_padroes <- trunc((dim(x)[1])/tam_janela)
  dataset <- matrix(x,nrow=tam_janela,ncol=nro_padroes)
  dataset <- t(dataset)
  plot(dataset[,tam_janela])
  x<-dataset[,1:tam_janela-1]
  y<-dataset[,tam_janela]
  x_train <- dataset[, 1:tam_janela-1]
  y_train <- dataset[, tam_janela]
  data <- splitForTrainingAndTest(x_train, y_train, ratio = 0.20)
  
  model <- mlp(data$inputsTrain, data$targetsTrain, size = c(2),
               learnFuncParams = c(0.9),
               maxit = epoch,
               learnFunc = "Std_Backpropagation",
               hiddenActFunc = "Act_Logistic",
               inputsTest = as.data.frame(data$inputsTest),
               targetsTest = data$targetsTest,
               linOut = TRUE)
  
  weightMatrix(model)
  extractNetInfo(model)
  
  plotIterativeError(model)
  
  predictions <- predict(model,data$inputsTrain)
  plot(seq(1,length(data$targetsTrain)),data$targetsTrain,xlab="x",ylab="y",type="p",col="blue",pch=1,cex=1.5)
  points(predictions,type="p",col="orange",pch=16)
  
  predictions <- predict(model,as.data.frame(data$inputsTest))
  plot(seq(1,length(data$targetsTest)),data$targetsTest,xlab="x",ylab="y",type="p",col="blue",pch=1,cex=1.5)
  points(predictions,type="p",col="orange",pch=16)
  
}
```

```{r previsões com 5 dias}
previsao_demanda(5)
```
```{r previsões com 10 dias}
previsao_demanda(10)
```

```{r previsões com 15 dias}
previsao_demanda(15)
```

```{r previsões com 20 dias}
previsao_demanda(20)
```
